2023-11-28 12:25:59 ERROR Unable to initialize WebDriver
2023-11-28 12:25:59 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 390, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcom-cIj6ROMf-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 101, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x55b5086245e3 <unknown>
#1 0x55b5082e70b7 <unknown>
#2 0x55b508334f53 <unknown>
#3 0x55b508335051 <unknown>
#4 0x55b50837a9c4 <unknown>
#5 0x55b50835bf1d <unknown>
#6 0x55b508377b3d <unknown>
#7 0x55b50835bcc3 <unknown>
#8 0x55b5083270e4 <unknown>
#9 0x55b5083280ae <unknown>
#10 0x55b5085eace1 <unknown>
#11 0x55b5085eeb7e <unknown>
#12 0x55b5085d84b5 <unknown>
#13 0x55b5085ef7d6 <unknown>
#14 0x55b5085bbdbf <unknown>
#15 0x55b508612748 <unknown>
#16 0x55b508612917 <unknown>
#17 0x55b508623773 <unknown>
#18 0x7f1b74894ac3 <unknown>

2023-11-28 12:26:02 ERROR Unable to initialize WebDriver
2023-11-28 12:26:02 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 390, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcom-cIj6ROMf-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 101, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: