2024-01-26 15:13:38 ERROR Elements not present after 0.5 seconds on page: https://capital.com/de/was-ist-cfd-handel
2024-01-26 15:13:38 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 293, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-cIj6ROMf-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x55ba627ddf83 <unknown>
#1 0x55ba62496cf7 <unknown>
#2 0x55ba624e699e <unknown>
#3 0x55ba624e6aa1 <unknown>
#4 0x55ba62531d64 <unknown>
#5 0x55ba625100dd <unknown>
#6 0x55ba6252f006 <unknown>
#7 0x55ba6250fe53 <unknown>
#8 0x55ba624d7dd4 <unknown>
#9 0x55ba624d91de <unknown>
#10 0x55ba627a2531 <unknown>
#11 0x55ba627a6455 <unknown>
#12 0x55ba6278ef55 <unknown>
#13 0x55ba627a70ef <unknown>
#14 0x55ba6277299f <unknown>
#15 0x55ba627cb008 <unknown>
#16 0x55ba627cb1d7 <unknown>
#17 0x55ba627dd124 <unknown>
#18 0x7f0698894ac3 <unknown>

2024-01-26 15:13:44 ERROR Elements not present after 0.5 seconds on page: https://capital.com/de/was-ist-cfd-handel
2024-01-26 15:13:44 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 293, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-cIj6ROMf-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x55ba627ddf83 <unknown>
#1 0x55ba62496cf7 <unknown>
#2 0x55ba624e699e <unknown>
#3 0x55ba624e6aa1 <unknown>
#4 0x55ba62531d64 <unknown>
#5 0x55ba625100dd <unknown>
#6 0x55ba6252f006 <unknown>
#7 0x55ba6250fe53 <unknown>
#8 0x55ba624d7dd4 <unknown>
#9 0x55ba624d91de <unknown>
#10 0x55ba627a2531 <unknown>
#11 0x55ba627a6455 <unknown>
#12 0x55ba6278ef55 <unknown>
#13 0x55ba627a70ef <unknown>
#14 0x55ba6277299f <unknown>
#15 0x55ba627cb008 <unknown>
#16 0x55ba627cb1d7 <unknown>
#17 0x55ba627dd124 <unknown>
#18 0x7f0698894ac3 <unknown>