2024-01-26 15:16:01 ERROR Elements not present after 0.5 seconds on page: https://capital.com/es/guia-de-estrategias
2024-01-26 15:16:01 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 293, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-cIj6ROMf-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x556d42c02f83 <unknown>
#1 0x556d428bbcf7 <unknown>
#2 0x556d4290b99e <unknown>
#3 0x556d4290baa1 <unknown>
#4 0x556d42956d64 <unknown>
#5 0x556d429350dd <unknown>
#6 0x556d42954006 <unknown>
#7 0x556d42934e53 <unknown>
#8 0x556d428fcdd4 <unknown>
#9 0x556d428fe1de <unknown>
#10 0x556d42bc7531 <unknown>
#11 0x556d42bcb455 <unknown>
#12 0x556d42bb3f55 <unknown>
#13 0x556d42bcc0ef <unknown>
#14 0x556d42b9799f <unknown>
#15 0x556d42bf0008 <unknown>
#16 0x556d42bf01d7 <unknown>
#17 0x556d42c02124 <unknown>
#18 0x7f6041294ac3 <unknown>

2024-01-26 15:16:06 ERROR Elements not present after 0.5 seconds on page: https://capital.com/es/guia-de-estrategias
2024-01-26 15:16:06 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 293, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-cIj6ROMf-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x556d42c02f83 <unknown>
#1 0x556d428bbcf7 <unknown>
#2 0x556d4290b99e <unknown>
#3 0x556d4290baa1 <unknown>
#4 0x556d42956d64 <unknown>
#5 0x556d429350dd <unknown>
#6 0x556d42954006 <unknown>
#7 0x556d42934e53 <unknown>
#8 0x556d428fcdd4 <unknown>
#9 0x556d428fe1de <unknown>
#10 0x556d42bc7531 <unknown>
#11 0x556d42bcb455 <unknown>
#12 0x556d42bb3f55 <unknown>
#13 0x556d42bcc0ef <unknown>
#14 0x556d42b9799f <unknown>
#15 0x556d42bf0008 <unknown>
#16 0x556d42bf01d7 <unknown>
#17 0x556d42c02124 <unknown>
#18 0x7f6041294ac3 <unknown>