2024-01-26 15:07:40 ERROR Elements not present after 0.5 seconds on page: https://capital.com/fr/comment-trader-cfd
2024-01-26 15:07:40 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 293, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-cIj6ROMf-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x5599bd65cf83 <unknown>
#1 0x5599bd315cf7 <unknown>
#2 0x5599bd36599e <unknown>
#3 0x5599bd365aa1 <unknown>
#4 0x5599bd3b0d64 <unknown>
#5 0x5599bd38f0dd <unknown>
#6 0x5599bd3ae006 <unknown>
#7 0x5599bd38ee53 <unknown>
#8 0x5599bd356dd4 <unknown>
#9 0x5599bd3581de <unknown>
#10 0x5599bd621531 <unknown>
#11 0x5599bd625455 <unknown>
#12 0x5599bd60df55 <unknown>
#13 0x5599bd6260ef <unknown>
#14 0x5599bd5f199f <unknown>
#15 0x5599bd64a008 <unknown>
#16 0x5599bd64a1d7 <unknown>
#17 0x5599bd65c124 <unknown>
#18 0x7f5a97c94ac3 <unknown>

2024-01-26 15:07:46 ERROR Elements not present after 0.5 seconds on page: https://capital.com/fr/comment-trader-cfd
2024-01-26 15:07:46 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 293, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-cIj6ROMf-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x5599bd65cf83 <unknown>
#1 0x5599bd315cf7 <unknown>
#2 0x5599bd36599e <unknown>
#3 0x5599bd365aa1 <unknown>
#4 0x5599bd3b0d64 <unknown>
#5 0x5599bd38f0dd <unknown>
#6 0x5599bd3ae006 <unknown>
#7 0x5599bd38ee53 <unknown>
#8 0x5599bd356dd4 <unknown>
#9 0x5599bd3581de <unknown>
#10 0x5599bd621531 <unknown>
#11 0x5599bd625455 <unknown>
#12 0x5599bd60df55 <unknown>
#13 0x5599bd6260ef <unknown>
#14 0x5599bd5f199f <unknown>
#15 0x5599bd64a008 <unknown>
#16 0x5599bd64a1d7 <unknown>
#17 0x5599bd65c124 <unknown>
#18 0x7f5a97c94ac3 <unknown>