2023-11-28 14:18:18 ERROR Unable to initialize WebDriver
2023-11-28 14:18:18 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 390, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcom-cIj6ROMf-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 101, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x5604bc1375e3 <unknown>
#1 0x5604bbdfa0b7 <unknown>
#2 0x5604bbe47f53 <unknown>
#3 0x5604bbe48051 <unknown>
#4 0x5604bbe8d9c4 <unknown>
#5 0x5604bbe6ef1d <unknown>
#6 0x5604bbe8ab3d <unknown>
#7 0x5604bbe6ecc3 <unknown>
#8 0x5604bbe3a0e4 <unknown>
#9 0x5604bbe3b0ae <unknown>
#10 0x5604bc0fdce1 <unknown>
#11 0x5604bc101b7e <unknown>
#12 0x5604bc0eb4b5 <unknown>
#13 0x5604bc1027d6 <unknown>
#14 0x5604bc0cedbf <unknown>
#15 0x5604bc125748 <unknown>
#16 0x5604bc125917 <unknown>
#17 0x5604bc136773 <unknown>
#18 0x7f3d23e94ac3 <unknown>