2024-01-26 16:03:43 ERROR Elements not present after 0.5 seconds on page: https://capital.com/es/trade-commodities
2024-01-26 16:03:43 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 293, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-cIj6ROMf-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x55fa6007bf83 <unknown>
#1 0x55fa5fd34cf7 <unknown>
#2 0x55fa5fd8499e <unknown>
#3 0x55fa5fd84aa1 <unknown>
#4 0x55fa5fdcfd64 <unknown>
#5 0x55fa5fdae0dd <unknown>
#6 0x55fa5fdcd006 <unknown>
#7 0x55fa5fdade53 <unknown>
#8 0x55fa5fd75dd4 <unknown>
#9 0x55fa5fd771de <unknown>
#10 0x55fa60040531 <unknown>
#11 0x55fa60044455 <unknown>
#12 0x55fa6002cf55 <unknown>
#13 0x55fa600450ef <unknown>
#14 0x55fa6001099f <unknown>
#15 0x55fa60069008 <unknown>
#16 0x55fa600691d7 <unknown>
#17 0x55fa6007b124 <unknown>
#18 0x7f6c5ea94ac3 <unknown>

2024-01-26 16:04:08 ERROR Elements not present after 0.5 seconds on page: https://capital.com/trading/platform/
2024-01-26 16:04:08 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 293, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-cIj6ROMf-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x55fa6007bf83 <unknown>
#1 0x55fa5fd34cf7 <unknown>
#2 0x55fa5fd8499e <unknown>
#3 0x55fa5fd84aa1 <unknown>
#4 0x55fa5fdcfd64 <unknown>
#5 0x55fa5fdae0dd <unknown>
#6 0x55fa5fdcd006 <unknown>
#7 0x55fa5fdade53 <unknown>
#8 0x55fa5fd75dd4 <unknown>
#9 0x55fa5fd771de <unknown>
#10 0x55fa60040531 <unknown>
#11 0x55fa60044455 <unknown>
#12 0x55fa6002cf55 <unknown>
#13 0x55fa600450ef <unknown>
#14 0x55fa6001099f <unknown>
#15 0x55fa60069008 <unknown>
#16 0x55fa600691d7 <unknown>
#17 0x55fa6007b124 <unknown>
#18 0x7f6c5ea94ac3 <unknown>